### ISSUE TITLE
a-c is busted

### ISSUE THREAD

**Issue by escapewindow** [mozilla-l10n/android-l10n-tooling#38]
```
[task 2021-07-27T23:40:31.646Z] executing ['create-l10n-branch', '--repo', 'mozilla-mobile/android-components', '--branch', 'android-components-quarantine', 'android-l10n']
[task 2021-07-27T23:40:31.883Z] Traceback (most recent call last):
[task 2021-07-27T23:40:31.883Z]   File "/usr/local/bin/create-l10n-branch", line 8, in <module>
[task 2021-07-27T23:40:31.883Z]     sys.exit(main())
[task 2021-07-27T23:40:31.883Z]   File "/usr/local/lib/python3.7/site-packages/mozxchannel/git/process.py", line 341, in main
[task 2021-07-27T23:40:31.883Z]     graph = handle(args.target, args.branch, args.repo, pull=args.pull)
[task 2021-07-27T23:40:31.883Z]   File "/usr/local/lib/python3.7/site-packages/mozxchannel/git/process.py", line 25, in handle
[task 2021-07-27T23:40:31.883Z]     graph.loadRevs()
[task 2021-07-27T23:40:31.883Z]   File "/usr/local/lib/python3.7/site-packages/mozxchannel/git/process.py", line 62, in loadRevs
[task 2021-07-27T23:40:31.883Z]     for n, branch in enumerate(repo.branches()):
[task 2021-07-27T23:40:31.883Z]   File "/usr/local/lib/python3.7/site-packages/mozxchannel/git/repository.py", line 70, in branches
[task 2021-07-27T23:40:31.883Z]     rev = self.lookup_branch(self.branch).target
[task 2021-07-27T23:40:31.883Z] AttributeError: 'NoneType' object has no attribute 'target'
```

Something to do with branch updates again.
I'd love to solve the root problem here, but a workaround of creating a bogus branch may also be acceptable for now.

**Comment by escapewindow** [comment]
With some debugging, I figured out we're trying to reference the branch `master` in android-components:

```
+ create-l10n-branch --repo mozilla-mobile/android-components --branch android-components-quarantine android-l10n --pull-request=main
branch master path mozilla-mobile/android-components
```

with this patch:

```diff
diff --git a/src/mozxchannel/git/repository.py b/src/mozxchannel/git/repository.py
index a6534aa..af01a17 100644
--- a/src/mozxchannel/git/repository.py
+++ b/src/mozxchannel/git/repository.py
@@ -67,6 +67,7 @@ def target_root(self):

     def branches(self, rev=None):
         if rev is None:
+            print(f"branch {self.branch} path {self.path}")
             rev = self.lookup_branch(self.branch).target
         tree = self[rev].tree
         if 'l10n.toml' not in tree:
```

... the fix is probably [here](https://github.com/mozilla-l10n/android-l10n-tooling/pull/37#issuecomment-887929435).

Essentially, to debug, load and run build-docker-image-l10n docker image, mounting your android-l10n-tooling dir.
Then in the docker container:

```
# uninstall mozxchannel, install it with `python setup.py develop` in /builds/android-l10n-tooling
#!/bin/bash
set -e -x

export TASKCLUSTER_ROOT_URL=https://firefox-ci-tc.services.mozilla.com/
# this is a hacked
# https://github.com/mozilla-l10n/android-l10n-tooling/blob/master/taskcluster/docker/l10n/git-credential-taskcluster
# where I echo a bogus username+pw and bypass the taskcluster secrets call
cp /builds/android-l10n-tooling/git-creds-nosecret /usr/local/bin/git-credential-taskcluster
mkdir -p /builds/worker/checkouts/src/mozilla-mobile
rm -rf /builds/worker/checkouts/src/android-l10n
rm -rf /builds/worker/checkouts/src/mozilla-mobile/android-components
git clone https://github.com/mozilla-l10n/android-l10n /builds/worker/checkouts/src/android-l10n
git clone https://github.com/mozilla-mobile/android-components /builds/worker/checkouts/src/mozilla-mobile/android-components
cd /builds/worker/checkouts/src
set +e
create-l10n-branch --repo mozilla-mobile/android-components --branch android-components-quarantine android-l10n --pull-request=main
```

**Comment by escapewindow** [comment]
https://github.com/mozilla-l10n/android-l10n/pull/367
